#!/usr/bin/env bash

CONFIG_FILE="$HOME/.config/tmx/tmx.conf"
DEFAULT_PATH=($HOME $HOME/personal/)
declare -a WINDOWS
declare -a COMMANDS

have_config() {
    if [ -f "$CONFIG_FILE" ]; then
	return 0
    else
	return 1
    fi
}

set_default_path() {
    if have_config; then
	raw_value=$(grep "^path=" "$CONFIG_FILE" | cut -d'=' -f2)
	content="${raw_value:1:-1}"
	read -r -a DEFAULT_PATH <<< "$content"
	# echo "${DEFAULT_PATH[@]}"
    else
	# echo "${DEFAULT_PATH[@]}"
	return 0 
    fi
}

has_sessionizer() {
    path=$1
    
    if [ -f "$path/.sessionizer.conf" ]; then
	# echo "Tem arquivo"
	return 0
    else
	# echo "Não tem arquivo"
	return 1
    fi
} 
get_attribute() {
    attribute=$1
    path="$2"
    # echo "path inside attribute $path"

    if has_sessionizer $path; then
	raw_value=$(grep "^$attribute=" "$path/.sessionizer.conf" | cut -d'=' -f2)
	content="${raw_value:1:-1}"
	if [ $attribute == "windows" ]; then
	    read -r -a WINDOWS <<< "$content"
	    # echo "${WINDOWS[@]}"
	    # return 0
	else
	    read -r -a COMMANDS <<< "$content"
	    # echo "${COMMANDS[@]}"
	fi
    else
	# echo "There's no $attribute"
	return 1
    fi
}

# TODO: sanitize to remove last / if have
# fix: it is not necessary. By default, dir in fzf does not have this list slash
get_session_name() {
    path=$1
    name=$(echo $1 | rev | cut -d'/' -f1,2 | rev)
    echo "$name"
}

in_tmux() {
    if [ -z $TMUX ]; then
	return 1
    else
	return 0
    fi
}

valid_path() {
    path=$1

    if [[ -e  $path ]]; then
	return 0
    else
	return 1
    fi
}

validate_session() {
    local session=$1

    if tmux has-session -t "$session" 2>/dev/null; then
	return 0
    else
	return 1
    fi
}

is_empty(){
    local session=$1

    if [ -z "$session" ]; then
	return 1
    else
	return 0
    fi

}

list_active_sessions() {
    tmux list-sessions -F "#{session_last_attached} [TMUX] #S" | sort -rn | cut -d' ' -f2-
}

get_inactive_dirs() {
    local active_sesssions=$(list_active_sessions)

    find "${DEFAULT_PATH[@]}" -maxdepth 1 ! -name '.*' -type d -print0 | while IFS= read -r -d '' dir; do
    local session_dir=$(get_session_name $dir)

    list_active_sessions | grep -q $session_dir
    if [ $? != 0 ]; then 
	echo $dir
    fi
done
}

fzf_dir() {
    if ! tmux has-session 2>/dev/null; then
	find "${DEFAULT_PATH[@]}" -maxdepth 1 ! -name '.*' -type d | fzf
    else
       {
	   tmux list-sessions -F "#{session_last_attached} [TMUX] #S" | sort -rn | cut -d' ' -f2-
	   get_inactive_dirs
       } | fzf
    fi
}

remove_tmux_prefix() {
    local prefixed_session=$1
    echo "$prefixed_session" | cut -d' ' -f2
}

load_sessionizer(){
    local session=$1
    local path=$2
    get_attribute "windows" $path
    get_attribute "commands" $path

    if [[ ${#WINDOWS[@]} || ${#COMMANDS[@]} ]]; then
	for i in "${!WINDOWS[@]}"; do
	    if [ $i == 0 ]; then
		tmux rename-window -t 1 "${WINDOWS[0]}"
		tmux send-keys -t "$session":1 "${COMMANDS[0]}" Enter

	    else
		# echo "Window ${WINDOWS[$i]}" 
		# echo "Command ${COMMANDS[$i]}"
		tmux neww -c $path -d -n "${WINDOWS[$i]}" "${COMMANDS[$i]}; zsh"
	    fi
	done
    else
	echo "nao executou"
    fi
}

create_or_attach_session() {
    path=$(fzf_dir)
    session=$(get_session_name $path)
    # has_session=$(tmux has-session -t "$session" 2>/dev/null)
    active_session=$(remove_tmux_prefix "$path")
    
    if in_tmux; then
	if ! tmux has-session -t "$session" 2>/dev/null && ! tmux has-session -t "$active_session" 2>/dev/null; then
	    valid_path "$path"
	    if [ "$?" != 0 ]; then
		echo "No valid path/session selected"
		return 1
	    fi
	    # echo "criando nova sessão"
	    tmux new -s "$session" -c $path -d

		get_attribute "windows" $path
		get_attribute "commands" $path
		if [[ ${#WINDOWS[@]} -gt 0 && ${#COMMANDS[@]} -gt 0 ]]; then
		    # echo "executando arquivo de config"
		    sleep 0.1
		    tmux send-keys -t "$session":1 "tmux new-window -n temporary -t 100" Enter
		    tmux send-keys -t "$session":1 "clear" Enter
		    sleep 0.1
		    for i in "${!WINDOWS[@]}"; do
			# echo "entrando no loop"
			local next=$((i+1))

			# echo "Next: $next"
			# echo "I: $i"
			# echo "Session: $session"

			if [ "$i" -eq 0 ]; then
			    tmux send-keys -t "$session":100 "tmux rename-window -t $next ${WINDOWS[$i]}" Enter
			    tmux send-keys -t "$session":$next "${COMMANDS[$i]}" Enter
			else
			    sleep 0.1
			    tmux send-keys -t "$session":100 "tmux neww -n ${WINDOWS[$i]}" Enter
			    sleep 0.05
			    tmux send-keys -t "$session":$next "${COMMANDS[$i]}" Enter
			fi
		    done
		    # sleep 0.1
		    tmux send-keys -t "$session":100 "tmux kill-window -t 100" Enter
		fi
		tmux switch-client -t "$session":1
	else
	    is_empty "$active_session"
	    if [ "$?" != 0 ]; then
		echo "No valid path/session selected"
		return 1
	    fi
	    # local active_session=$(remove_tmux_prefix $session)
	    tmux switch-client -t "$active_session"
	fi
    else

	if ! tmux has-session -t "$session" 2>/dev/null && ! tmux has-session -t "$active_session" 2>/dev/null; then
	    valid_path "$path"
	    if [ "$?" != 0 ]; then
		# echo $active_session
		echo "$active_session is a invalid path"
		return 1
	    fi
	    tmux new-session -d -s "$session" -c "$path"
	    load_sessionizer "$session" "$path"

	    tmux attach-session -t "$session"
	else
	    # validate_session "$active_session"
	    is_empty "$active_session"
	    if [ "$?" != 0 ]; then
		echo "No valid path/session selected"
		return 1
	    fi
	    tmux attach-session -t "$active_session"
	fi
    fi
}

set_default_path 
create_or_attach_session 
